CREATE TABLE IF NOT EXISTS viewers (
    id INT AUTO_INCREMENT PRIMARY KEY,
    ip_address INT(4) UNSIGNED NOT NULL,
    user_agent TEXT NOT NULL,
    page_url VARCHAR(255) NOT NULL,
    views_count INT NOT NULL,
    view_date DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
)